#!/bin/bash

chmod 600 ./keypair.pem || exit

rsync -avr --rsh="ssh -i keypair.pem -o StrictHostKeyChecking=no" --delete-after --delete-excluded _site/ travis_ftp@jaysinh.com:/blog/ || exit

rm ./keypair.pem || exit
