#!/bin/bash

./scripts/build

pwd

ls -al

rsync -avr --rsh="ssh -i keypair.pem -o StrictHostKeyChecking=no" --delete-after --delete-excluded _site/ travis_ftp@jaysinh.com:/home/travis_ftp/html/blog/
